project_id = "dqddeokbxzbmlbsltige"

[functions.invitar-integrante]
verify_jwt = true

[functions.aceptar-invitacion]
verify_jwt = true

[functions.login-usuario]
verify_jwt = false

[functions.bot-whatsapp]
verify_jwt = false
